# yaml-language-server: $schema=../experiment.schema.json
seed: 0
name: ???
run_dir: runs/${name}/seed${seed}
data:
  train:
    $class: project.SineWave
    n: 256
    noise: 0.1
    seed: ${seed}
  test:
    $class: project.SineWave
    n: 256
    noise: 0.1
    seed: 1234
loss:
  $ref: torch.nn.functional.mse_loss
epochs: 100
batch_size: 32
