# yaml-language-server: $schema=../app.schema.json
server:
  $class: webapp.server.Server
  host: 127.0.0.1
  port: 8000
  workers: 1
  secret_key: ???
database:
  $class: webapp.db.SQLite
  url: sqlite:///webapp.db
cache:
  $class: webapp.cache.RedisCache
  url: redis://${server.host}:6379
  ttl: 10m
jobs: ~import jobs.yaml#jobs
log_dir: logs
